api = "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"

[ai_prompt]
summary = """
You're a professional data analyst. Analyze the dataset shown below:

{data}

Give a concise summary including:
- What the dataset is about (1–2 sentences)
- The most important columns and what they represent
- Any major trends or missing data issues
- Key statistical highlights (e.g. variation, outliers)
- A short list of the most useful visualizations to understand the data

Keep it clear and short. Avoid repeating column names unless necessary.

"""
